### ISSUE TITLE
[FEATURE REQUEST] Target Hours API

### ISSUE THREAD

**Issue by nethad** [hundertzehn/mocoapp-api-docs#101]
An API to retrieve target hours vs. actual hours.

**Comment by agileapplications** [comment]
![image](https://user-images.githubusercontent.com/235900/107615441-7f0ffa80-6c4c-11eb-9078-364da613847e.png)

**Comment by agileapplications** [comment]
Done: https://github.com/hundertzehn/mocoapp-api-docs/pull/120/files
