### ISSUE TITLE
[FEATURE REQUEST] Invoice Tags updatable

### ISSUE THREAD

**Issue by dennisoderwald** [hundertzehn/mocoapp-api-docs#106]
In MocoApp we use the labels/tags as intermediate states to control automation internally. It would be really great if we could update an invoice.

An endpoint like https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/invoices.md#put-invoicesidupdate_status would be sufficient to update the tags.

Is this possible in the short term?

**Comment by agileapplications** [comment]
Yes I think we'll manage it @dennisoderwald But give us the November ok?

**Comment by dennisoderwald** [comment]
Ok, awesome @agileapplications :)

**Comment by agileapplications** [comment]
@dennisoderwald Please see the latest update: https://github.com/hundertzehn/mocoapp-api-docs/commit/b59f446738a221521e3c2ea7f3f44e1f5ac77e4b
