### ISSUE TITLE
[QUESTION] Tags/Labels editable for Deals

### ISSUE THREAD

**Issue by Songworks** [hundertzehn/mocoapp-api-docs#107]
Hello there,

Is it possible to PUSH/PUT the tags/labels through the `deals`-endpoint?
The field isn't mentioned in the `deals` PUSH-documentation, so I'm guessing it's currently not possible.

The `companies`-endpoint has this feature so I tried it the same way for `deals`. I submitted the field as either `labels` or `tags` and the value being an array of strings, but no luck. Also tried it with a comma-separated list out of desperation, but nope.

If it's currently not possible at all. Could we put it down as a feature request? :)

On an almost related note: The `deals`-endpoint allows a field `person_id` (ContactsPeople for a Deal) to be pushed, but this field isn't mentioned in the PUSH-documention. It worked though.

Thanks in advance and cheers!

**Comment by pic** [comment]
Thanks @Songworks for yiour feedback. I've updated the doc: https://github.com/hundertzehn/mocoapp-api-docs/commit/becf7830e945774ef0662a36171ebed4d1c15665

We are working on a solution to update tags for any entity, including deals. Probably we will also add tags directly on deals POST and PUT.

**Comment by agileapplications** [comment]
@Songworks Please check the latest update: https://github.com/hundertzehn/mocoapp-api-docs/commit/b59f446738a221521e3c2ea7f3f44e1f5ac77e4b

There is a general endpoint now to manage the tags/labels.

**Comment by Songworks** [comment]
@agileapplications Works great, thank you very much for you guys fast work! Cheers!
