### ISSUE TITLE
make clickup valid as remote_service

### ISSUE THREAD

**Issue by iboargun** [hundertzehn/mocoapp-api-docs#108]
we are trying to customize the moco browser extension to work with clickup. We forked the extension and customized it already. The only issue currently is that the remote_service we send to the activites api call sends invalid "remote_service" back. can you please activate clickup as a valid value in the api? otherwise we have to mock this service as trello or something else...

if you also build in the link to clickup tasks, the expected urls are like:
https://app.clickup.com/t/{task_id}

**Comment by agileapplications** [comment]
Hi @iboargun yes we can do it. What is the string you send here? I guess "clickup" right?

Best, Tobias

**Comment by agileapplications** [comment]
@iboargun We will allow "clickup" as service. Is that fine or any reasons against it?

**Comment by pic** [comment]
@iboargun "clickup" should now be accepted as a valid remote_service.
Regardin the link, it's something that it's managed on the client, it's the browser extension that sends to MOCO the desired `remote_url`. Best regards

**Comment by iboargun** [comment]
hi sorry, just saw your answers and comments. yes "clickup" is fine.
and if you add this in remoteServices.js in your extension, we could use your official extension for our clickup instance.

`clickup: {
    name: "clickup",
    host: "https://app.clickup.com",
    urlPatterns: [
      ":host:/t/:id",
      ":host:/t/:id/:customId",
      ":host:/:space/v/l/f/:folder"
    ],
    description: (document, service, { id, customId }) => {
      const title = document.querySelector(".task-name__overlay")?.textContent?.trim()
      return `#${customId || id} ${title || ""}`.trim()
    },
    allowHostOverride: false,
  },`

**Comment by manubo** [comment]
Hi @iboargun, we will add clickup to the removeServices.js for the next release.
