### ISSUE TITLE
[BUG] Holiday hours not set when created via curl

### ISSUE THREAD

**Issue by sommalia** [hundertzehn/mocoapp-api-docs#111]
Hello,
we noticed when creating holiday credits, via the api, that the hours property was not set after creating the holiday entry.

When created via curl request:

`curl -X POST 'https://{domain}.mocoapp.com/api/v1/users/holidays'   -H 'Authorization: Token token={TOKEN}' -H 'Content-Type: application/json' -d '{ "user_id": 1234, "year": 2020, "title": "Holiday credits", "hours": 20 }'`

Response:
```
{
  "id": 1234,
  "year": 2020,
  "title": "Holiday credits",
  "days": 2.5,
  "hours": 0,
  "user": {
    "id": 1234,
    "firstname": "test",
    "lastname": "test"
  },
  "created_at": "2020-12-23T10:37:26Z",
  "updated_at": "2020-12-23T10:37:26Z"
}
```

When the holiday is created over the web app, then retrieved over the api, the the data looks like this:

```    
{
  "days": 2.5,
  "hours": 20,
  "id": 1234,
  "title": "Holiday credits",
  "user": {
    "id": 12345,
    "firstname": "test",
    "lastname": "test"
  },
  "year": 2020,
  "created_at": "2020-12-24T10:43:11Z",
  "updated_at": "2020-12-24T10:43:11Z"
}
```
Thank you and merry christmas :)

**Comment by sunsations** [comment]
Hi @sommalia 

Thanks for informing us. We take care of in the next couple of working days 👍 

Wish you also merry Christmas

**Comment by sunsations** [comment]
Hi @sommalia 

It's fixed. Please provide "days" in your input instead of "hours":


````
curl -X POST 'https://{domain}.mocoapp.com/api/v1/users/holidays' -H 'Authorization: Token token={TOKEN}' -H 'Content-Type: application/json' -d '{ "user_id": 1234, "year": 2020, "title": "Holiday credits", "days": 20 }'
````

Kind regards
Thomas
