### ISSUE TITLE
[FEATURE REQUEST] Set internal rates via API

### ISSUE THREAD

**Issue by fabianmax** [hundertzehn/mocoapp-api-docs#113]
Hi there,

it would be great to have the ability of setting internal rates via the API.

**Comment by agileapplications** [comment]
We'll have a look into it @fabianmax and get back to you :+1:

**Comment by nethad** [comment]
@fabianmax There is now an endpoint for internal hourly rates: https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/account/internal_hourly_rates.md
