### ISSUE TITLE
[FEATURE REQUEST] Get Project Payment Schedules

### ISSUE THREAD

**Issue by agileapplications** [hundertzehn/mocoapp-api-docs#119]
Like GET /projects/{project_id}/payment_schedules -> GET /projects/payment_schedules

PARAMS:
* from, to (date of the payment schedule)
* checked true/false
* company_id (if easy possible)

**Comment by nethad** [comment]
Done: https://github.com/hundertzehn/mocoapp-api-docs/pull/124
