### ISSUE TITLE
[BUG] Contact on the invoice is now always set to the API user

### ISSUE THREAD

**Issue by dennisoderwald** [hundertzehn/mocoapp-api-docs#130]
When we generated an invoice without set the contact, the project manager was displayed on the invoice or the contact of the customer.

Now the API user who generates the invoice always appears. I have also not found a variable in the API documentation to change this again.

It would be great if it would just use the project manager like before (if not set).

**Comment by agileapplications** [comment]
Hi @dennisoderwald 

You can override the contact passing the `internal_contact_id`. We also added that now to the serialized attributes.

Best Tobias
