### ISSUE TITLE
Webhook NodeJS example

### ISSUE THREAD

**Issue by crstnre** [hundertzehn/mocoapp-api-docs#135]
I have trouble generating the correct signature with NodeJS.

Could you add an example for that?

My code so far:

```javascript
const signature = crypto.createHmac('sha256', 'key')
  .update(
    JSON.stringify(event) // Tried with the whole event/body object and only { id, description }.
  )
  .digest('hex')
```

Edit: I've tried your example Ruby code and compared the signature with my NodeJS result – they are identical. I assume the payload is wrong. How should I convert the object to string and WHICH object to convert?

**Comment by crstnre** [comment]
I now came up with a rough solution, but that works only for a few events.

```javascript
const signature = crypto.createHmac('sha256', 'key')
  .update(
    new Buffer(steps.trigger.raw_event.body_b64, 'base64').toString('ascii')
  )
  .digest('hex')
```

**Comment by agileapplications** [comment]
Hi @crstnre, can you post an example with a specific payload and the signature you expect?

**Comment by crstnre** [comment]
Hey @agileapplications,

thanks for the response.

I have sent examples to Thomas via the Moco chat. Sorry, but I am a bit nervous to share the payload publicly.

We are investigating this issue currently. Maybe you could contact him to collaborate on that issue.

**Comment by crstnre** [comment]
Thomas has mentioned that events with Umlauts were not working. The string was converted to ASCII, not UTF8.

Working solution:

```js
Buffer.from(steps.trigger.raw_event.body_b64, 'base64').toString('utf8')
```
