### ISSUE TITLE
[FEATURE REQUEST] letter_paper_id for invoices

### ISSUE THREAD

**Issue by Dure2000** [hundertzehn/mocoapp-api-docs#146]
It would be great, if we could supply a letter_paper_id for invoices (/invoicess/{id}.pdf?letter_paper_id=12345) too, as it is for offers! At the moment it's just blank or standard

**Comment by agileapplications** [comment]
We'll consider this @Dure2000 👍

**Comment by nethad** [comment]
@Dure2000 This is now possible: https://github.com/hundertzehn/mocoapp-api-docs/pull/174

**Comment by Dure2000** [comment]
👍👍👍😍

Tobias Miesel ***@***.***> schrieb am Mi., 15. Dez. 2021,
08:28:
