### ISSUE TITLE
[FEATURE REQUEST] send_email endpoint for offers

### ISSUE THREAD

**Issue by Dure2000** [hundertzehn/mocoapp-api-docs#147]
It would be great, if we could submit a  POST /offers/{id}/send_email for offers too, as it is for invoices! and of course provide a letter_paper_id in both cases :-)

Thanks
Ralf Schwalbe

**Comment by agileapplications** [comment]
@Dure2000 Makes sense. We'll plan this.

**Comment by nethad** [comment]
@Dure2000 This is now possible: https://github.com/hundertzehn/mocoapp-api-docs/pull/172
