### ISSUE TITLE
Project tasks not filtered by `updated_after`

### ISSUE THREAD

**Issue by Hauke1979** [hundertzehn/mocoapp-api-docs#148]
Hey zusammen, irgendwie klappt bei mir updated_after nicht ... 

https://xxxx.mocoapp.com/api/v1/projects/xxxx/tasks?updated_after=2019-12-05T10:39:09Z

Was mache ich falsch?

Danke für einen kurzen Tipp und viele Grüße,
Hauke

**Comment by agileapplications** [comment]
Hi @Hauke1979 

Ich denke der Satz aus der Doku _For synchronization **almost all** resources can be filtered by updated_after passing a time in UTC, as ISO8601 format._ ist hier der Grund.

Wir schauen, ob man das auch hier ermöglichen kann. In anderen Endpunkten klappt es aber?

Gruss Tobias

**Comment by Hauke1979** [comment]
Hi @agileapplications, danke für Deine schnelle Rückmeldung. Das habe ich mir auch schon gedacht.

Unsere Anforderung wäre, nur die aktualisierten Tasks zuzugreifen - am besten auch ohne Project Id ...

Bisher haben wir es nur bei Usern probiert, da hat es nicht geklappt - ist aber auch kein Thema da. Ich prüfe das gleich noch mal für Activities ...

**Comment by Hauke1979** [comment]
Bei projects geht es schon mal 👍

**Comment by nethad** [comment]
Konnte via Support geklärt werden. Es handelt sich um einen Bug, wir beheben den :+1:
