### ISSUE TITLE
Provide a way to access timesheet data

### ISSUE THREAD

**Issue by tehplague** [hundertzehn/mocoapp-api-docs#149]
I'd like to ask for an API endpoint that allows us to fetch timesheet data (i.e. the amount of work spent in a project grouped by the configured tasks).
The data returned by the endpoint should roughly be the same as given by Moco at `https://<your_domain>.mocoapp.com/projects/<project_id>/timesheet`.  Preferably this endpoint should allow to specify the time range for which the data is collected, i.e. the current or the last month or even a custom range.

What do you think?

**Comment by nethad** [comment]
Hi @tehplague, we'll get back to you on that, it could take a little longer due to holiday absences though...

**Comment by agileapplications** [comment]
@tehplague Happy and healthy new year 🎉 

You already have the timesheet data by using the `/activities` endpoint:
https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/activities.md#get-activities

You should filter by `project_id` and `from`, `to`. The only thing missing would be the grouping by task which is a presentational concern that should be easily done manually. The API provides the raw data.

Best Tobias

**Comment by tehplague** [comment]
Excellent, works for me. Thank you, @agileapplications @nethad !
