### ISSUE TITLE
[FEATURE REQUEST] Add Soll-Ist report data

### ISSUE THREAD

**Issue by jansauer** [hundertzehn/mocoapp-api-docs#152]
Wir würden gern automatisiert auf zu große Abweichung von Mitarbeitern im Soll-Ist Performance Report reagieren können. Beispiel hierfür wäre eine Slack Nachricht wenn der Mitarbeiter mehr als 24 Stunden in der Erfassung zu seinem Soll fehlen oder auch wenn er zu viel arbeitet.

Leider kann ich aktuell in der API nichts zu Soll-Ist Reports finden. Zwar git es die zugrunde liegenden Daten aber ein Nachbau der Auswertung ist kompliziert und Fehleranfällig.

**Comment by agileapplications** [comment]
Nehmen wir auf @jansauer. Kann noch nichts genaues durchgeben, aber den Report nachbauen macht wirklich keinen Sinn, da hast du Recht.

**Comment by danieldormann** [comment]
Hi @agileapplications,

gibt es hierzu Neuigkeiten? Generell wäre es schön auf die Reports zugreifen zu können. Gibt es dazu auch Pläne?

**Comment by nethad** [comment]
@jansauer @danieldormann 

Habt ihr diesen Endpunkt schon gesehen? https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/users.md#get-usersidperformance_report

Der wäre dafür vorgesehen, fehlt euch da was?

**Comment by danieldormann** [comment]
@nethad Das ist mir entgangen. Vielen Dank!

**Comment by nethad** [comment]
@danieldormann Alles klar :+1:

**Comment by lecodeski** [comment]
Ich hatte kürzlich auch den Soll-Ist gesucht und bin auch euere Diskussion gestoßen. Der Endpunkt wäre auch für mich genau das was ich suche.  
Leider bekomme ich immer einen 403 zurück – obwohl ich in der Web-UI mein eigenen Soll-Ist natürlich einsehen kann. Auch alles andere wie Activity erstellen geht mit dem gleichen Api-Key und User-ID.

Kann das sein, dass das Rechte-mäßig wo anders aufgehangen ist?
