### ISSUE TITLE
[FEATURE REQUEST] Invoice DELETE

### ISSUE THREAD

**Issue by dennisoderwald** [hundertzehn/mocoapp-api-docs#153]
Currently it is not possible to delete an invoice, since we work a lot with draft invoices temporarily, we want to automate this step and delete invoices.

**Comment by agileapplications** [comment]
@dennisoderwald Please check and reopen if it doesn't work as expected https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/invoices.md#delete-invoicesid
