### ISSUE TITLE
[BUG] POST /activities/disregard -> 404 (when payload is invalid)

### ISSUE THREAD

**Issue by dennisoderwald** [hundertzehn/mocoapp-api-docs#154]
When using the `POST /activities/disregard` endpoint, we noticed that if no payload or an incorrect payload is submitted, only a 404 is returned and not a 400 with the error message.

**Comment by agileapplications** [comment]
We see what we can do here! We planned some resources for March to work on API requests.

**Comment by nethad** [comment]
@dennisoderwald This should now be fixed an giving you a proper error message :+1:
