### ISSUE TITLE
No Label/Tag for Deal

### ISSUE THREAD

**Issue by rawdlite** [hundertzehn/mocoapp-api-docs#156]
I need to create a label/tag for a Deal via the API.

```curl -X POST \
  'https://{domain}.mocoapp.com/api/v1/deals' \
  -H 'Authorization: Token token={Api Token}' \
  -H 'Content-Type: application/json' \
  -d '{
        "name": "Test for Labels",
        "currency": "EUR",
        "money": "25000",
	"status":  "won",
        "reminder_date": "2018-12-01",
        "user_id": 933610511,
        "deal_category_id": 30498,
        "tags": ["testlabel"]
      }'
```

Response is

```
{"id":364153,"name":"Test for Labels","status":"won","reminder_date":"2018-12-01","closed_on":"2022-01-28","money":25000.0,"currency":"EUR","info":"","tags":[],"custom_properties":{},"user":{"id":933610511,"firstname":"anon","lastname":"ymous"},"person":null,"customer":null,"company":null,"category":{"id":30498,"name":"Mündliche Zusage /Termin","probability":90},"created_at":"2022-01-28T15:40:13Z","updated_at":"2022-01-28T15:40:13Z"} 
```

So the Deal got created, yet the label was not set. "tags":[]
Am i missing something?

cheers tom

**Comment by nethad** [comment]
@rawdlite Does the tag already exist on deals in general?

**Comment by rawdlite** [comment]
The tag exists in moco but had not been assigned to any deals yet.
Will test that.

**Comment by rawdlite** [comment]
Tested with an existing and assigned Tag.
No success

**Comment by agileapplications** [comment]
@rawdlite You cannot update the entry directly. You need to go via this endpoint: https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/tags.md

Can you try this?

**Comment by rawdlite** [comment]
Thank you! The tagging endpoint works for me.
Being able to set a tag when creating a deal with a single call would be sweet, though.

**Comment by sunsations** [comment]
Functionality to create deals with tag assignmens is now possible.
