### ISSUE TITLE
[FEATURE REQUEST] projects/expenses tags filter

### ISSUE THREAD

**Issue by dennisoderwald** [hundertzehn/mocoapp-api-docs#157]
We would like to filter the endpoint by tags.

**Comment by agileapplications** [comment]
There are not tags on expenses @dennisoderwald or do you mean by project tags (labels)?

**Comment by dennisoderwald** [comment]
@agileapplications project tags, yes, sorry.

**Comment by nethad** [comment]
@dennisoderwald This is now implemented: https://github.com/hundertzehn/mocoapp-api-docs/pull/173
