### ISSUE TITLE
get projects to create activities

### ISSUE THREAD

**Issue by mcnilz** [hundertzehn/mocoapp-api-docs#16]
How to get the project and task IDs as user that does not have access to projects? In the webclient the IDs are included as JSON inside the HTML and the webclient is not using the API. But how to create activity entries through the API? GET /api/v1//projects should at least return the projects with tasks that are available for the user.

**Comment by agileapplications** [comment]
Hi @mcnilz 

We will check this asap. You are totally right that the web app is using a different approach that is not yet included in our public api.

Let me get back to you the coming days.
Best Tobias

**Comment by agileapplications** [comment]
This is your endoint @mcnilz 
https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/projects.md#get-projectsassigned
