### ISSUE TITLE
[FEATURE REQUEST] GET /projects missing coLeader

### ISSUE THREAD

**Issue by dennisoderwald** [hundertzehn/mocoapp-api-docs#163]
API endpoints around projects are missing the return of the "coLeader" - in the first step the output would be good, in the long term also writing when creating and updating from a project.

**Comment by nethad** [comment]
@dennisoderwald  This is already there in the `co_leader` field but was not documented, we now adapted the docs: https://github.com/hundertzehn/mocoapp-api-docs/pull/171
