### ISSUE TITLE
[FEATURE REQUEST] Creating a payment for a purchase

### ISSUE THREAD

**Issue by heldinz** [hundertzehn/mocoapp-api-docs#166]
I am trying to automate the processing of credit card expenses from a CSV via the API. So far I can create a new purchase, but I cannot see how to add a _payment_ for that purchase. Although I can see how to [retrieve payments for a purchase](https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/purchases.md#attributes), I don't see how I can create a new payment, either when [creating a new purchase](https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/purchases.md#post-purchases) or afterwards. The only reference I can find for creating a payment is [creating an invoice payment](https://github.com/hundertzehn/mocoapp-api-docs/blob/8b8bfbab52697a516964e6086cfd68001afceb43/sections/invoice_payments.md#post-invoicespayments), which to my understanding is a very different thing.

Could you please clarify whether or not it is possible to add a payment for a purchase via the API, and if so, how? Thank you!

**Comment by nethad** [comment]
Hi @heldinz 

It's not currently possible, we are preparing to enhance the API in March and it's likely that we will be able to implement this then, but I cannot promise yet.

We can update you as soon as we have a decision on the scope.

**Comment by heldinz** [comment]
Thanks for your reply @nethad! An update when you're ready would be great, thanks 🙏🏻

**Comment by nethad** [comment]
Hi @heldinz 

Good news, this is now done: https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/purchase_payments.md

:partying_face:

**Comment by heldinz** [comment]
Thanks so much, @nethad! 🎉
