### ISSUE TITLE
[FEATURE REQUEST] GET /deals with offers

### ISSUE THREAD

**Issue by dennisoderwald** [hundertzehn/mocoapp-api-docs#167]
I noticed that there is no way to retrieve the offers from a deal/lead. It would be good to get the offer ID's or the complete object below a deal or at least the possibility to filter for a deal in GET /offers.

**Comment by nethad** [comment]
@dennisoderwald This filter is now implemented: https://github.com/hundertzehn/mocoapp-api-docs/pull/179

**Comment by dennisoderwald** [comment]
A filter makes perfect sense. Would an array with the ID's in the actual entity also be possible? @nethad

**Comment by nethad** [comment]
@dennisoderwald It shouldn't be a problem, I'll look into this

**Comment by nethad** [comment]
@dennisoderwald This is done now: https://github.com/hundertzehn/mocoapp-api-docs/pull/182
