### ISSUE TITLE
500 error code response on POST request to `/purchases`

### ISSUE THREAD

**Issue by heldinz** [hundertzehn/mocoapp-api-docs#183]
I'm testing sending a series of POST requests to the `/purchases` endpoint, and one or more requests consistently fail with a 500 error response. At first it was always the same one, so I thought it was something to do with that, but after repeated testing, sometimes the original failing one passes and sometimes multiple requests fail. I would have thought rate-limiting was the reason, except that I'm getting 500 errors instead of 429s.

Each payload looks roughly like this (details obfuscated). Any help figuring this out appreciated!

```
{
    "date": "2022-03-01",
    "currency": "EUR",
    "payment_method": "credit_card",
    "receipt_identifier": "1234567",
    "items": [
        {
            "title": "XXXXXXX",
            "total": 19.35,
            "tax": 0,
            "tax_included": true,
            "category_id": ""
        }
    ],
    "file": {
        "filename": "1234567.pdf",
        "base64": "JVBER...=="
    }
}
```

**Comment by nethad** [comment]
Hi @heldinz 

Have you tried submitting it without the file block? Does it work then?
You could also try to push the via file: https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/purchases.md#patch-purchasesidstore_document

If you think it's the file, please write us on support@mocoapp.com or via In-App-Service and reference this issue. Thanks!

**Comment by nethad** [comment]
@heldinz  I've checked the logs and I think I found the issue: the `identifier` you provided was already taken, it has to be unique. We'll check that this error is reported correctly.

**Comment by heldinz** [comment]
@nethad Thanks for looking into this! I am still receiving intermittent errors after implementing the throttling so this is helpful.

Do you mean the `receipt_identifier`? Unfortunately I've now tried leaving this off the request entirely but I still get a 500 error.

**Comment by nethad** [comment]
@heldinz I realized this is something you cannot influence via API, so it's actually a configuration problem of the purchase identifiers ("Nummernkreise") that creates duplicates of purchase identifiers, so this is a configuration problem on your Moco account. Please reach out to us on support@mocoapp.com and reference this issue, so we can sort this out :+1:

**Comment by heldinz** [comment]
@nethad Thank you, will do!

**Comment by agileapplications** [comment]
@heldinz We advised you to have a throttling on your side so far. If this pops up again please don't hesitate to file a new issue. I would consider this a bug on our side then. Not so easy to fix tough (would take some time).
