### ISSUE TITLE
[FEATURE REQUEST] Project Expenses Filter for custom properties

### ISSUE THREAD

**Issue by dennisoderwald** [hundertzehn/mocoapp-api-docs#185]
For the endpoints `GET /projects/expenses` and `GET /projects/{id}/expenses` we work a lot with the custom properties. So far it is not possible to filter on an endpoint using the custom properties, but that would be super helpful. Maybe this is an option to implement.

**Comment by agileapplications** [comment]
Tough one... very expensive operation right now considering the implementation we have so far. Will not be ready soon 🤷‍♂️

**Comment by nethad** [comment]
This is now possible, see: https://hundertzehn.github.io/mocoapp-api-docs/entities.html#filter-by-custom-fields--custom_properties
