### ISSUE TITLE
[FEATURE REQUEST] Invoice Items with expense_id or a array of attached expense_id's

### ISSUE THREAD

**Issue by dennisoderwald** [hundertzehn/mocoapp-api-docs#187]
At the moment there is no possibility to retrieve the expenses of an invoice neither via filter nor own endpoint.

Timesheets are possible but not the expenses.

With `GET /invoices/:id` you get an array with the items but the `service_type` is always `null` and you don't get an expense id. Neither collected nor per item.

**Comment by agileapplications** [comment]
@dennisoderwald The `service_type` is a different feature not yet release in the UI. I understand your point 👍

**Comment by agileapplications** [comment]
#191
