### ISSUE TITLE
[FEATURE REQUEST] Invoice timesheet difference true/false

### ISSUE THREAD

**Issue by dennisoderwald** [hundertzehn/mocoapp-api-docs#188]
In mocoapp it is indicated when an invoice deviates from the actual timesheet (=> `Die Stunden wurden manuell angepasst und stimmen möglicherweise nicht mit dem Stundenauszug überein.`). This information would be very useful in the API to be able to react to it.

**Comment by nethad** [comment]
Hi @dennisoderwald 

This is now implemented: https://github.com/hundertzehn/mocoapp-api-docs/pull/220
