### ISSUE TITLE
Issue with activity time

### ISSUE THREAD

**Issue by shaikh1896** [hundertzehn/mocoapp-api-docs#189]
I am having some issue, when i am updating any thing my my project which was created previously, same was not getting updated in data which i am calling through api. pls help

**Comment by agileapplications** [comment]
@shaikh1896 Can you try to rephrase your issue? I don't understand what you are going after... 🤷‍♂️ Any anonymous examples?

**Comment by shaikh1896** [comment]
Yeah So i have updated one previously created activity in one of my project on moco app. But it is not showing up when i am calling the api. Also how many activities can i fetch per call?

**Comment by shaikh1896** [comment]
For example, i am fetching all activities in a project in two ways:
1. Running for just one day say 7th april 2022
2. Running it from 1 Jan 2022 till 8th april 2022.
But in first case i am getting 440 entries for 7th april whereas in second case i am just getting around 80 entries for 7th april.
Pls help
