### ISSUE TITLE
weekend call updates

### ISSUE THREAD

**Issue by tatianaperalta** [hundertzehn/mocoapp-api-docs#192]
hello,  
does the api also make weekend entries data avalilable right the same day these are created in moco? 
our function is sending daily updates during the weekdays but we did not receive new data today (monday), even when there were some entries made during this last weekend,

**Comment by nethad** [comment]
Hi @tatianaperalta 

Are you talking about the activities endpoint? If so, yes, also weekend entries are possible. Did you check on mocoapp.com, if they appear?

**Comment by tatianaperalta** [comment]
@nethad , thanks for your reply, 
yes, the entries did appear in mocoapp.com the same day of their creation (sunday), still yesterday (monday) the new data was not pushed to our database. And, today all previous entries were correctly pushed into our database (including sunday's entries), 

I wonder, is weekends' activity also available to the endpoint right away  after its creation? or, what could be causing that weekends' activity is not being updated mondays?

**Comment by shaikh1896** [comment]
@nethad what i understand is suppose if we create an activity today (20 april 2022) for 15 april 2022 (yes for the past) in moco app, it wont be coming in api call if we are calling it for 20th april 2022 right?

**Comment by nethad** [comment]
@tatianaperalta what do you mean by "pushed to our database"? Activities are immediately available after you POST them to the API endpoint, via API itself and also on mocoapp.com. If not, please give us an example of what you tried to do (best as a curl command, of course without any API keys) and give us an exact date and time you tried where it didn't work as expected.

@shaikh1896 Any activities you push (no matter what date) are immediately available.
