### ISSUE TITLE
Getting limited activities

### ISSUE THREAD

**Issue by shaikh1896** [hundertzehn/mocoapp-api-docs#194]
Hello,  i am not getting all activities within a timerange?
Is there a limit on number of entries (activities) return in api respons?
Thanks in Advance

I am using this code:
curl -X GET \
  'https://{domain}.mocoapp.com/api/v1/activities?from=2022-01-01&to=2022-04-20&project_id=' \
  -H 'Authorization: Token token=YOUR_API_KEY'

**Comment by sunsations** [comment]
@shaikh1896 Yes, we limit it to 100 entries. Please use the [Pagination](https://github.com/hundertzehn/mocoapp-api-docs#pagination) to get all entries.

**Comment by shaikh1896** [comment]
> @shaikh1896 Yes, we limit it to 100 entries. Please use the [Pagination](https://github.com/hundertzehn/mocoapp-api-docs#pagination) to get all entries.
I tried that also but it gives me same number of entries as before.
<https://{domain}.mocoapp.com/api/v1/projects.json?page=10>; rel="next"
