### ISSUE TITLE
missing fields in api-call for companies

### ISSUE THREAD

**Issue by svenroduner** [hundertzehn/mocoapp-api-docs#196]
I'm in need for the `identifier` from a company. In your documentation, it is stated that the complete object is returned which includes the `identifier`. Unfortunately, the response doesn't contain it. 
<br>
My specific Request is: `https://company.mocoapp.com/api/v1/companies`. I'm only getting half of the promised properties. [Companies - Attributes](https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/companies.md#attributes)

**Comment by nethad** [comment]
Hi @svenroduner the identifiers should be in there, just not in the order we document. Can you please try again and confirm?

**Comment by svenroduner** [comment]
Thanks for your response. I checked again and found out that the `identifier`-property is only in some entries and not in every. Is this how it should behave?

**Comment by svenroduner** [comment]
I used a different approach and don't need the `identifier` anymore. Thanks for your help.
