### ISSUE TITLE
Add Lead Time Range to API Response

### ISSUE THREAD

**Issue by fabianmax** [hundertzehn/mocoapp-api-docs#199]
Thanks for adding the new time range to lead/deals in the UI. I would like to receive them as well from the API endpoint. Are there any plans to add them in the future?

**Comment by sunsations** [comment]
It should be done in June 👍

**Comment by sunsations** [comment]
Available now 👍 

https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/deals.md
