### ISSUE TITLE
Example for an Activities-POST-Request is not working

### ISSUE THREAD

**Issue by euwa** [hundertzehn/mocoapp-api-docs#20]
The POST-Request for creating an activity is not working.
Calling Curl via console is triggering Field-Errors for "date" and "description" like...

"date":["muss ausgefüllt werden","ist nicht gültig"],
"description":["ist zu kurz (weniger als 3 Zeichen)"]

Calling the API via POSTMAN we will get only a "301 - Moved permanently"

Is there anything we didnt recognized? Thanks in advance.

Here the curl request:
curl -X POST 'https://nfq.mocoapp.com/api/v1/activities' \
                        -H "Authorization: Token token={moco_api_key}" \
                        -H 'Content-Type: application-json' \
                        -d '{"date": "2019-02-04", "description": "Moco Api test with more than 3 characters.", "hours": 1.0, "project_id": 944739918, "task_id": 1729356}'

**Comment by euwa** [comment]
Looks like it is a permission issue...
Closing this Issus

**Comment by agileapplications** [comment]
Thank you for getting back to us 👍
