### ISSUE TITLE
HTTP 500 Error when creating user employment without from and to

### ISSUE THREAD

**Issue by sommalia** [hundertzehn/mocoapp-api-docs#202]
Hello,

when creating an employment entry without ``from`` and ``to`` the api returns a HTTP 500 error. The entry is created on the backend but the client will receive an error.

These parameters are currently optional, see: https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/employments.md#post-usersemployments

Response

```bash
HTTP/2 500 Internal Server Error
Content-Type: text/plain
Vary: Origin
X-Runtime: 0.085144

500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.
```

**Comment by agileapplications** [comment]
@sommalia Thank you for your feedback. We'll check it and get back to you soon.

**Comment by agileapplications** [comment]
We applied a fix @sommalia. Please check again and re-open if not solved appropriately.
