### ISSUE TITLE
[BUG] POST to /receipts endpoint results in HTTP 500 error when billable=true

### ISSUE THREAD

**Issue by schakko** [hundertzehn/mocoapp-api-docs#205]
When POSTing a request to `/api/v1/receipts` and `billable` is set to `true` the server reponds with a HTTP 500.

cURL request made:

```bash
curl -X POST \
  'https://xyz.mocoapp.com/api/v1/receipts' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Token token=xyz' \
  -d '{"date":"2022-05-16","title":"test","info":"Test-Beschreibung","billable":true,"items":[{"vat_code_id":1011,"gross_total":20.1}]}'
```

Setting `billable` to `false` succeeds.

**Comment by agileapplications** [comment]
@schakko If you don't provide a project, the receipt cannot be billable is currently a constraint on our side. We'll add a better validation so that you don't get a 500 on this one.

**Comment by agileapplications** [comment]
@schakko You should get a proper 4XX error message in the future. Feel free to open again if sth is still unclear 👍
