### ISSUE TITLE
[FEATURE REQUEST] Allow setting purchase category when POSTing a receipt

### ISSUE THREAD

**Issue by schakko** [hundertzehn/mocoapp-api-docs#206]
When doing a POST request to `/api/v1/receipts`, the purchase category should be providable. At the moment it can neither be provided by the field `purchase_category` nor `purchase_category_id`.

**Comment by agileapplications** [comment]
@schakko We'll add it 👍

**Comment by nethad** [comment]
@schakko This is done now, check out: https://github.com/hundertzehn/mocoapp-api-docs/pull/235
