### ISSUE TITLE
Deleted invoices issue

### ISSUE THREAD

**Issue by ibali30** [hundertzehn/mocoapp-api-docs#209]
Hello,
I am currently working on a fintech projects which requires to periodically synchronise invoices from moco. I am noticing that moco gives the possibility to delete invoices, but is there a way to track the deleted invoices using Moco's apis so we can undertake actions based on deleted invoices?

**Comment by nethad** [comment]
Hi @ibali30 

Currently there's no way of tracking deleted invoices, you would have to use webhooks for that.
