### ISSUE TITLE
Date parameters not working 

### ISSUE THREAD

**Issue by ibali30** [hundertzehn/mocoapp-api-docs#210]
Hello,
I am trying to filter invoices and purchases by date params but this does not seem to work.
Here is how I do it:
![image](https://user-images.githubusercontent.com/77961480/181254214-ee72299b-4ed3-4bf6-963c-c6e3630c3fc4.png)

**Comment by nethad** [comment]
@ibali30 I assume you don't get any invoices back because you filter for invoices in the future (August 2022). Could that be the case?

**Comment by ibali30** [comment]
@nethad Nope, I get all the invoices, although them are created in the past

**Comment by nethad** [comment]
@ibali30 It looks like you have whitespaces in the URL, can you try to remove them (e.g. after `date_from`)

**Comment by ibali30** [comment]
@nethad It seems this is the case. Does the date represent the creation date or modification date?

**Comment by manubo** [comment]
@ibali30 The `date_from` and `date_to` dates filter the invoices by the date of the invoices.
