### ISSUE TITLE
No recipient company defined in invoices response

### ISSUE THREAD

**Issue by ibali30** [hundertzehn/mocoapp-api-docs#211]
Hey,
The sale invoice response does not include recipient company. This is not happening in purchases response.
Thanks

**Comment by nethad** [comment]
HI @ibali30 

Unfortunately it's not really clear what you mean here, could you specify the endpoint and the field you expect? Can you give an example output you would like to see?

Thank you!

**Comment by ibali30** [comment]
This is the endpoint:
curl -X GET \
  'https://{domain}.mocoapp.com/api/v1/invoices' \
  -H 'Authorization: Token token=YOUR_API_KEY'

So basically a sale invoice should also have a buyer. 
In other terms the contact is not part of the response:
![image](https://user-images.githubusercontent.com/77961480/183945590-c63c4905-953b-41cc-abd8-8bbf940d2f16.png)

**Comment by nethad** [comment]
This seems very specific to your use of custom fields. Please get in touch with us via our support channels.
