### ISSUE TITLE
Minor typo in documentation

### ISSUE THREAD

**Issue by centigrade-thomas-becker** [hundertzehn/mocoapp-api-docs#212]
In the companies function PUT the header key "Authorization" is spelled with a lower case A.
https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/companies.md#put-companiesid
```
curl -X PUT \
  'https://{domain}.mocoapp.com/api/v1/companies/{123}' \
  -H 'authorization: Token token=YOUR_API_KEY' \
  -H 'Content-Type: application/json' \
  -d '{
        "name": "Beispiel GmbH"
      }'
```

In the other entities, e.g. "contacts" the header key "Authorization" is spelled with a capital A
https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/contacts.md#put-contactspeopleid
```
curl -X PUT \
  'https://{domain}.mocoapp.com/api/v1/contacts/people/{id}' \
  -H 'Authorization: Token token=YOUR_API_KEY' \
  -H 'Content-Type: application/json' \
  -d '{
        "job_position": "Head of Sales"
      }'
```

It does not seem to make a functional difference how it is spelled. But the documentation should be consistent.

**Comment by agileapplications** [comment]
@centigrade-thomas-becker I fixed it 👍 https://github.com/hundertzehn/mocoapp-api-docs/commit/e104fb1b6019f72632b4190a849d67094466493c
