### ISSUE TITLE
Include payments and customer objects inside invoices response

### ISSUE THREAD

**Issue by ibali30** [hundertzehn/mocoapp-api-docs#215]
Hey,
I have noticed that customer and list of payments are not included in the response from this endpoint: 
GET /invoices
And we are killing our apps by performing two http calls for every sale invoice  in order to retrieve the payments and customer.
Can these be included in the invoice response?

**Comment by agileapplications** [comment]
@ibali30 We are looking into a way to query for those sub resources in a single query by proving sth like `?ids=1,2,3,4` to almost all endpoint. Will keep you updated.

**Comment by ibali30** [comment]
I think you can do the same thing as in purchases part. 
GET /purchases does include the payments in the response object, while GET /invoices does not

**Comment by nethad** [comment]
Hi @ibali30 

We won't include the objects, but it's now a lot more efficient to fetch them in one go, see: https://github.com/hundertzehn/mocoapp-api-docs/pull/224
