### ISSUE TITLE
Typo: API > Purchases > Attributes > Field 'title'

### ISSUE THREAD

**Issue by schakko** [hundertzehn/mocoapp-api-docs#231]
In the `Attributes` section of the [Purchases API](https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/purchases.md), there is a comma before the `title` property name in the JSON sample:

```json
{
  "id": 987,
  "identifier": "E2016-0001",
  "receipt_identifier": "KK121",
  ",title": "SBB Ticket",
  "info": null,
  "...": "...."
}
```

It should be

```json
{
  "id": 987,
  "identifier": "E2016-0001",
  "receipt_identifier": "KK121",
  "title": "SBB Ticket",
  "info": null,
  "...": "...."
}
```

**Comment by nethad** [comment]
Thanks @schakko it's fixed now: https://github.com/hundertzehn/mocoapp-api-docs/commit/5de4d924341589c9bd7a1549c53a63421d85b4c5
