### ISSUE TITLE
[FEATURE REQUEST] service_period in POST /invoices

### ISSUE THREAD

**Issue by dennisoderwald** [hundertzehn/mocoapp-api-docs#247]
At the `POST /invoices` endpoint, "service_period" cannot be set. You can only use service_period_from and service_period_to, which results in "01.12.2022 - 20.01.2023" appearing on the invoice instead of "12/2022 - 01/2023" appearing on the web interface invoice.

However, this leads to an ugly wrap on the invoice because in most cases the column is not wide enough from the layout.

**Comment by agileapplications** [comment]
@dennisoderwald If you send first date of the month and last date of the month as service period, MOCO should format it as you described. It's only of specific dates are passed we assume you want exactly those printed.

Can you confirm?

**Comment by agileapplications** [comment]
@dennisoderwald Can you confirm?

**Comment by dennisoderwald** [comment]
@agileapplications Sorry, very busy at the moment. I will try to give you feedback as soon as possible.

**Comment by agileapplications** [comment]
Feel free to open again, if this is not the case.
