### ISSUE TITLE
Consistency: Presences can be created through the API even if the period is locked

### ISSUE THREAD

**Issue by schakko** [hundertzehn/mocoapp-api-docs#248]
If a period is locked (e.g. before 1.1.2023), presences and activities can not be created through the user interface. However, presences can be created through `/users/presences` for that locked period.
For a locked period, either the presences should be editable in the UI or the endpoint should disallow changes.

**Comment by nethad** [comment]
Hi @schakko 

I cannot reproduce this issue here, can you contact us via the official support channel to sort this issue out? Thank you!
