### ISSUE TITLE
[FEATURE REQUEST] Adding "/profile/" entity

### ISSUE THREAD

**Issue by kirboit** [hundertzehn/mocoapp-api-docs#253]
I have an API Key that NOT allows me to see users. So may I ask you for adding "/profile/" entity to your API that allows you to see your profile details without access to all users. It may look something like this:

{
        "id": 933623535,
        "firstname": "Tom",
        "lastname": "Mayer",
        "active": true,
        "extern": false,
        "email": "tom.mayer@example.com",
        "mobile_phone": "01762135515",
        "work_phone": "017612312312",
        "home_address": "",
        "info": "",
        "birthday": "1976-04-09",
        "avatar_url": "https://data.mocoapp.com/objects/objects%2Faccounts%.."
        "tags": [],
        "custom_properties": {},
        "unit": {
            "id": 909157837,
            "name": "unitExample"
        },
        "created_at": "2020-05-04T16:25:38Z",
        "updated_at": "2023-02-06T12:19:54Z"
}

Thanks in advance for your support!

**Comment by nethad** [comment]
Hi @kirkakrut 

May I ask why you need this? What's your use case?

**Comment by kirkakrut** [comment]
> Hi @kirkakrut
> 
> May I ask why you need this? What's your use case?

I'm making some kind of custom statistics for all users in company, but I want to make it available for personal use.

**Comment by nethad** [comment]
@kirkakrut We'll look into this and might include it for our next round of API updates

**Comment by nethad** [comment]
Hi @kirboit 

This endpoint is now available: https://hundertzehn.github.io/mocoapp-api-docs/sections/profile.html
