### ISSUE TITLE
[DOCS RELATED] /offers documentation not matching with API

### ISSUE THREAD

**Issue by MaxiMilli** [hundertzehn/mocoapp-api-docs#263]
Small bug in the docs. If you perform a POST request to /v1/offers you have to send either a company_id/deal_id or a project_id in order to add a new offer. I think an asterisk (*) is missing or better pointed out, because the error was quite irritating:

![image](https://user-images.githubusercontent.com/15245005/230652770-aac222d8-70bb-4aaa-8a9d-6d8fc6720aa3.png)

and the same request with a company_id:
![image](https://user-images.githubusercontent.com/15245005/230652895-c6aaa616-8f52-4249-90e9-3ef0409c6c30.png)

Thanks in advance!

**Comment by nethad** [comment]
Hi @MaxiMilli 

This has now be clarified in the docs: https://github.com/hundertzehn/mocoapp-api-docs/pull/276

Thanks for letting us know :+1:
