### ISSUE TITLE
[FEATURE REQUEST] - endpoints for planned holidays and working hours schedules

### ISSUE THREAD

**Issue by halas** [hundertzehn/mocoapp-api-docs#27]
Hi!

We are using data from your api to show some personalized information on internal dashboard. 
And we would like to show three pieces of information that - if I understand correctly - are a bit difficult/impossible to get:

1. Status of current worked hours per user (if given user worked too much or too little in comparison to due hours at this day). Here if I understand well I could of course iterate over all activities and count hours manually, but it would be a tedious task that I would need to schedule to some cron once a day, probably?
2. Date of next planned holiday ( •ᴗ• )  - you added recently (https://github.com/hundertzehn/mocoapp-api-docs/commit/26467e7708830582e963807a8d5c8d32271fee70) an endpoint for  summary of holidays available to the user given year, but I can't get just get dates of planned holidays for given user, can I? Again, I would need to iterate through all schedules, filter by user, by name "Urlaub" and then find the closest, is that right? 
3. If we have users that work part time (for example work only Monday to Wednesday every week), I can not get this schedule (like week days/hours were user is supposed to be at the office), can I? I can only get weekly hour target for given user?

So my question is if I understand correctly that at current state of the api I can get information from point 1 and 2 only by manually iterating through Activities/Schedules respectively and I can't get information from point 3 at all?
And if my understanding indeed is correct, would you consider adding endpoints that would make getting those information in more straightforward way? :) 

Thanks in advance for your help!
Best regards from Aachen!

**Comment by pic** [comment]
Hi halas,
thanks for your feedback, your requests make totally sense and we will take them into consideration and get back to you as soon as possible. Best regards

**Comment by halas** [comment]
Thanks for your quick and positive feedback! Looking forward to hearing from you :)

**Comment by agileapplications** [comment]
A quick Update @halas - we will deliver this in 2-3 steps. Haven't forgot it.

**Comment by halas** [comment]
Fantastic, thanks for the update!

**Comment by agileapplications** [comment]
@halas 

1. [ ] Status of current worked hours per user
2. [x] Date of next planned holiday
3. [ ] weekly hour target for given user

Regarding 2. planned holidays, there is already https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/schedules.md#get-schedules

-> you can filter by `absence_code=4` and `from={current date}`

You will get all upcoming holidays/vacation. Will that help you?
Best Tobias

**Comment by halas** [comment]
It does indeed, I should be able to work with that, thank you!

**Comment by halas** [comment]
As to weekly hour target for given user though, It is not exactly my point, maybe I did not express myself clearly, sorry. 
What I would like to do is be able to show in our app if a person who works part time is expected to be at the office in the given moment. So it is more like a work schedule (not a regular absence). 
I think I can already get the weekly hour target, but it does not help for this purpose.

**Comment by agileapplications** [comment]
Ok, that clarifies it – so you are more interested in the "pattern". Monday morning off, Friday full day off etc.?

**Comment by halas** [comment]
exactly :)

**Comment by agileapplications** [comment]
@halas 

1. [ ] Status of current worked hours per user
2. [x] Date of next planned holiday
3. [x] weekly hour pattern for given user

Regarding 3. -> you'll find the pattern now in the attributes of the employment: https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/employments.md#attributes

Just one missing 👍

**Comment by halas** [comment]
This is fantastic! Thank you so much for working on this so quickly! 
Although, let me say I am worried about your work life balance at moco - it was Friday evening! ;)

**Comment by agileapplications** [comment]
@halas We have different schedules here at MOCO :-) Sometimes on the weekend, sometimes in the evening and sometimes we are off during the day to compensate. Although let me say we are highly motivated by feedback like yours 👍

**Comment by agileapplications** [comment]
@halas Just an update, that due do holiday season we have less resources here. It's not forgotten.

**Comment by halas** [comment]
Thanks for an update! No worries, we are going slower here too :)

**Comment by agileapplications** [comment]
@halas Will be done soon with https://github.com/hundertzehn/mocoapp-api-docs/issues/101

**Comment by agileapplications** [comment]
Hi @halas finally we were able to provide an endpoint where you can get the status of the current work hours per user: https://github.com/hundertzehn/mocoapp-api-docs/pull/120/files

Best Tobias

**Comment by halas** [comment]
thank you! so glad you develop this api :) keep up the good work! :)
