### ISSUE TITLE
I'm getting a 401 - Invalid API key (user API keys are disabled).

### ISSUE THREAD

**Issue by vdurante** [hundertzehn/mocoapp-api-docs#280]
Hey, sorry if this is not the correct place for asking this, but I couldn't find this in the docs nor the API docs, so I thought maybe I could ask here and suggest improving the API docs as well.

A user is attempting to connect his MOCO account in awork, but our backend is getting the following response when attempting to use the API:

```json
{
	"message": "Invalid API key (user API keys are disabled)."
}
```

Not sure what I should suggest the user to do to fix this issue. Could someone help me please?

Thanks!

**Comment by nethad** [comment]
Hi @vdurante 

This is a temporary issue, please get in touch with us via support, thank you!
