### ISSUE TITLE
[FEATURE REQUEST] Retrieve calculated Daily/Weekly Target Working Hours for Employees

### ISSUE THREAD

**Issue by PatrickBauer** [hundertzehn/mocoapp-api-docs#281]
Dear Moco API Team,

Our team is currently in the process of integrating more deeply with the Moco API and we have identified a feature that could significantly enhance our utilization of your service.

## Feature Description:

We would like to have the ability to retrieve the daily or weekly target working hours of an employee, essentially the scheduled working hours minus any deductions like vacations or other leaves.

This data is already available in MOCO's activity view, and accessing it directly would be much more convenient than calculating these values based on the user's employments, schedules, and other possible determining factors.

![image](https://github.com/hundertzehn/mocoapp-api-docs/assets/1428943/f3796960-5004-4f44-b261-b90781f8d287)

## Technical Details:

Ideally, the API endpoint would look something like this:

```
GET /users/target-working-hours/{year}

{
  "user": {
    "id": 933590696,
    "firstname": "John",
    "lastname": "Doe"
  },
  "week_number": 36,
  "week_start_date": "2023-09-04",
  "week_end_date": "2023-09-08",
  "weekly_target_hours": 29.75,
  "daily_pattern": {
    "monday": 0,
    "tuesday": 8.5,
    "wednesday": 8.5,
    "thursday": 8.5,
    "friday": 4.25
  }
}

```

## Benefits

* More precise project planning and resource allocation
* Allows for better management and overview of employee work schedules.

We believe that this feature would not only benefit our organization, but many others who rely on your services for efficient operation.

Thank you for considering our request. We look forward to the possibility of seeing this feature in a future update of the Moco API.

Best regards,
Patrick from @mayflower

**Comment by nethad** [comment]
Hi Patrick

Have you seen this endpoint already? https://hundertzehn.github.io/mocoapp-api-docs/sections/users.html#get-usersidperformance_report

You get the monthly numbers there. Can you explain why you need the weekly numbers? What's the use case you want to solve?

**Comment by PatrickBauer** [comment]
Hey @nethad,

This endpoint currently only returns the total hours tracked. However, for our internal tracking, it would be really beneficial to have insight into the number of billable hours tracked as well.

While we could potentially adapt to work with monthly tracked billable hours, having the data available on a weekly basis would enable us to monitor this in smaller, more manageable intervals.

**Comment by mickimnet** [comment]
To extend to what @PatrickBauer already wrote: we want a percentage comparison between billable hours and working hours (called `Sollstunden` in German). That doesn't need to be on a weekly basis, monthly should be fine. We just didn't find an API endpoint to get the number.

**Comment by nethad** [comment]
@PatrickBauer @mickimnet 

Would it already help if we add billable hours to the monthly report here? https://hundertzehn.github.io/mocoapp-api-docs/sections/users.html#get-usersidperformance_report

**Comment by davidhimmelberger** [comment]
> To extend to what @PatrickBauer already wrote: we want a percentage comparison between billable hours and working hours (called `Sollstunden` in German). That doesn't need to be on a weekly basis, monthly should be fine. We just didn't find an API endpoint to get the number.

Seconding this, building a dashboard with billable vs. tracked hours on a weekly basis would be key for us.

**Comment by PatrickBauer** [comment]
@nethad That would already help yes, although billable hours per period is relatively easy to accumulate, unlike the target working hours which depend on many different sources of data.

**Comment by nethad** [comment]
@PatrickBauer @mickimnet 

Our aim is to give a monthly view, according to this view:

![image](https://github.com/hundertzehn/mocoapp-api-docs/assets/222981/796f7e54-f9ff-4b4c-b9d9-63a9a20fc94b)

If we can extend the user performance report like this (new field `billable_hours`):

```json5
{
  // ...
  "monthly": [
    {
      "year": 2023,
      "month": 1,
      "target_hours": 128.0,
      "billable_hours": 102.0,
      "hours_tracked_total": 133.71,
      "variation": 5.71
    },
    // ...
  ]
}
```

would make it more feasible. At the moment I don't see us adding weekly numbers I'm afraid.

What do you think?

**Comment by PatrickBauer** [comment]
@nethad 
Yes, that would be great, thank you.
