### ISSUE TITLE
Zugriff API /users/{id}/performance_report 403

### ISSUE THREAD

**Issue by Stefan-Schulze-SIMTEVA** [hundertzehn/mocoapp-api-docs#292]
Ich soll die Auslastungsdaten der Mitarbeiter berechnen. Dafür möchte ich auf die API /users/{id}/performance_report zugreifen.
Ich erhalte immer einen 403 Fehler. Mein API Key darf eigentlich alles in MOCO machen. 
Das folgen der Anleitung ist leider nicht erfolgreich. Ist das ein BUG in der API, oder gibt es einen geheim kniff?

[/users/{id}/performance_report](https://hundertzehn.github.io/mocoapp-api-docs/sections/users.html#get-usersidperformance_report)
Nach Anleitung 

curl -X GET \
  'https://{domain}.mocoapp.com/api/v1/users/{id}/performance_report' \
  -H 'Authorization: Token token=YOUR_API_KEY'

**Comment by nethad** [comment]
Hallo @Stefan-Schulze-SIMTEVA 

Bitte melde dich bei uns im In-App-Service oder via E-Mail beim Support, damit wir das anschauen können. Danke dir!
