### ISSUE TITLE
[FEATURE REQUEST] Ability to restrict endpoint access for account API keys

### ISSUE THREAD

**Issue by Daniel199438** [hundertzehn/mocoapp-api-docs#299]
Hello Moco API team,

First of all, thank you for the great API.

Our company would like to implement some automation using the Moco API. We noticed that the API key provides access to either all or no endpoints and between read and write mode.

Could the system be expanded further and a similar rights access system like to Moco Workspace accounts added?
The goal is that the API can only access project data in write or read mode, for example, but should not have access for personal data from workspace accounts in order to ensure data protection and security.

Best regards,

Daniel

**Comment by nethad** [comment]
Hi Daniel

If you want more fine-granular permissions, please use a user's key: https://hundertzehn.github.io/mocoapp-api-docs/authentication.html

The user key can only read and write according to the user's permissions. If you need further assistance or have more questions, please get in touch with us via support, thanks!
