### ISSUE TITLE
purchases / assign_to_project not working?

### ISSUE THREAD

**Issue by abendschoen** [hundertzehn/mocoapp-api-docs#302]
Hey there ;)
I was playing around with some automations and tried to assign a purchase to a project with the endpoint POST /purchases/{id}/assign_to_project like mentioned in the docs - but I always got a 404. Tried different setups / data combinations. Nothing works. Always 404. Is it an error in the API or is it me?
![assign_to_project_not_possible](https://github.com/hundertzehn/mocoapp-api-docs/assets/82140828/d9538459-79a2-4917-bf15-688034d296f1)

**Comment by sunsations** [comment]
Looks like one of the "id"s is not correct and thus "not found" (404). Please make sure that all "id" exists.

Better if you get in contact over our in-app support, as you don't have to disguise your ID there and we can help you better.
