### ISSUE TITLE
How to stop a running Timer/Task

### ISSUE THREAD

**Issue by X-Tender** [hundertzehn/mocoapp-api-docs#32]
I can start the timer for a Task if I set the `hours` value to 0. But how can I stop it? Currently I just could only start a new one and then delete it immediately :)

I tried it via `PATCH: /projects/{project_id}/stop_timer` like it's being called on the website but it didn't worked out .

**Comment by agileapplications** [comment]
Hi @X-Tender 

That is a great feedback – and we will provide a solution for that. Give us a few days 👍 

Best
Tobias

**Comment by X-Tender** [comment]
Great, keep in mind that additionally to the "stop timer" a "continue timer" call will be required 😄

**Comment by agileapplications** [comment]
Here you go @X-Tender https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/activities.md#patch-activitiesidstart_timer

Continuing is also possible with that endpoint.
