### ISSUE TITLE
[FEATURE REQUEST]: Allow PUT for certain attributes for invoices

### ISSUE THREAD

**Issue by Dure2000** [hundertzehn/mocoapp-api-docs#334]
Hi there
Thank you again for providing a robust API that helps us streamline our processes. However, we noticed a limitation when working with invoices via the API: while it’s possible to update the status of an invoice, there is no option to assign custom tags (labels) to invoices.

Use Case
Being able to assign tags to invoices would greatly improve organizational workflows. For example:

- Marking invoices with specific tags for internal categorization (e.g., "factoring").
- Automating tagging via webhooks based on client attributes or other triggers.
- Using tags to enhance reporting and filtering in invoice management.

Legal Context: We understand and appreciate the legal reasons behind restricting certain changes to invoices. However, since tags have no legal or financial implications on the invoice itself, this feature would not conflict with those constraints.

Proposed Solution

- Extend the API to allow PUT requests on invoices to manage tags.
- Ensure tags can be added, removed, and listed without altering any core invoice data (e.g., amounts, client info, etc.).

**Comment by nethad** [comment]
Hi @Dure2000 

Adding labels is already possible in a generic way: https://hundertzehn.github.io/mocoapp-api-docs/sections/tags.html

**Comment by Dure2000** [comment]
Hi nethad,

thanks, I wasn't aware of that option, ... should do the job!
