### ISSUE TITLE
Missing field 'hours' in GET /activities

### ISSUE THREAD

**Issue by andywenk** [hundertzehn/mocoapp-api-docs#35]
Hey there,

first of all thanks for the awesome API implementation. I am wondering, why I can't see the field `hours` in the response when requesting this URL:

`https://OUR_SUBDOMAIN.mocoapp.com/api/v1/activities?from=2019-01-01&page=2&project_id=PROJECT_ID&to=2019-01-31&user_id=`

The fields are:

`id,date,description,billed,billable,tag,remote_service,remote_id,remote_url,project/id,project/name,project/billable,task/id,task/name,task/billable,customer/id,customer/name,user/id,user/firstname,user/lastname,timer_started_at,created_at,updated_at`

I checked, if there is an entry and it should be 2,25 hours.

Do I miss something?

Thanks and all the best

Andy

**Comment by pic** [comment]
`hours` should definitely be there and I can see it doing a test with our account. Do you get the entry and the field is missing?

**Comment by andywenk** [comment]
Uh gosh - that was a strange bug. I use a little gem called json-to-csv an there was this bug I fixed in this PR: https://github.com/cescue/json-to-csv/pull/1/commits/c9d46c487b6fbe4820e1508696eaffab1bca4ed9

Thanks for the very quick look at this issue ;-)

All the best

Andy
