### ISSUE TITLE
Server responds with timeout

### ISSUE THREAD

**Issue by andywenk** [hundertzehn/mocoapp-api-docs#36]
Hi again,

due to the fact, that the API is responding in shards by 100 entries, but the data I need are much more, I calculated the number of pages (iterations) I need to get the full data set. I am reading the header "x-total". So in this example I need 81 iterations, to get all data:

`~/p/s/m/moco_api git:master ❯❯❯ bundle exec bin/moco_api activities --from=2019-02-01 --to=2019-02-28 --export_csv `

After each iterations request I set a `sleep(5)`. That are 5 seconds to wait. Unfortunately I receive this after the first 8 to 18 iterations:

`Iterations: 81  
................bundler: failed to load command: bin/moco_api (bin/moco_api)
Faraday::TimeoutError: Failed to open TCP connection to BLABLA.mocoapp.com:443 (Operation timed out - connect(2) for "BLABLA.mocoapp.com" port 443)`

I am aware, that you are limiting the request by writing in the docs:

`You can expect to be able to fire 15 requests within a time frame of 15 seconds. If you exceed this limit, the server responds with 429 Too Many Requests.`

But in my case I don't fire one request in one second or 15 in 15 seconds and I don't get a 429 code. 

Do I miss something here? It was last night 30.04.2019 between 10:00 pm and 01.05.2019 01:00 am.

Additional question: is there a way to avoid the 100 lines result per request?

Thanks a lot for any advise or help.

Cheers

Andy (sumcumo.com)

**Comment by agileapplications** [comment]
Hi @andywenk 

Unfortunately there is no way around that pagination. It's the only way we can keep MOCO smooth and fast for everyone. Maybe we have other options in the future 👍 

Regarding your problem, that is not easy for us to reproduce. It reads more like a network issue (maybe disconnects from Wifi etc.?). Try to make 20 requests without a sleep and you should get some 429s. 

Best Tobias

**Comment by andywenk** [comment]
Hey @agileapplications ,

ok that sounds feasible. I just removed the sleep and was able to get more than 15 responses without a 429. So I suspect, that my (indeed Wifi) connection is very slow and unstable 😆 

I am back in the office on monday and will test with LAN and fast Internet.

Thanks

Andy

**Comment by agileapplications** [comment]
Ok great to hear – feel free to reopen the issue 👏 Happy integrating!
