### ISSUE TITLE
Create invoices as drafts

### ISSUE THREAD

**Issue by petersentner** [hundertzehn/mocoapp-api-docs#37]
Is it planned that invoices can also be created as drafts via the API?

We have fixed-term contracts with many customers. All of these are single projects in Moco. Some customers also have several contracts (and also projects). At the beginning of the month, we create an invoice for each customer for all contracts they have.

We would like to automate this process using the API. We have already created a script for this. But we would prefer to create the invoices as drafts, as we will partly add manual items.

Thanks

Peter

**Comment by agileapplications** [comment]
Hi @petersentner 

Now that you brought it up, you can consider it planned 👍 It makes totally sense. The invoicing endpoint is still in it's beginning. @pic Can you plan this and inform @petersentner afterwards?

Best Tobias

**Comment by pic** [comment]
Hi @petersentner 

it should work already passing `status: "draft"`, I've updated the documentation with this information.
Please let me know if there are any issue, thx

**Comment by petersentner** [comment]
Great! - I tested it, it works for me.
