### ISSUE TITLE
[FEATURE REQUEST] Endpoints for planned billing

### ISSUE THREAD

**Issue by petersentner** [hundertzehn/mocoapp-api-docs#38]
Hi Moco Team,

as part of our planned automation of accounting, we would like to use the API to "plan billing".
(In German "Abrechnung planen").
I am looking forward to your feedback if this feature makes sense for you or not?

Greetings Peter

**Comment by agileapplications** [comment]
Hi @petersentner 

You are aware that this is today only available on fixed price projects?
We can make this public as well. Let me get back to you. I have to clarify some things first.

Best Tobias

**Comment by agileapplications** [comment]
It will take some timer @petersentner, we haven't forgotten...

**Comment by agileapplications** [comment]
Hi @petersentner, we have limited resources due to holiday season and also there might be structural changes to extend this also for time and material based projects with might change the api. We need some more time to thing this through. I leave it open until then.

Best Tobias

**Comment by petersentner** [comment]
Hi @agileapplications,

thanks for your feedback. We are still working on our accounting processes and at the moment everything is delayed. But it's still useful for us and nice to see that it will come sometime.
Our goal is to reduce the monthly outgoing invoices by 2020 through standing invoices (in German: Dauer-Rechnung) and then to collect the monthly planned amounts from all customers by direct debit.
Maybe it fits in with your schedule.

Greetings Peter

**Comment by AlexandreKilian** [comment]
@agileapplications any news on the status of making this public? We would need that for a similar use case

**Comment by agileapplications** [comment]
Yes guys - it's basically online. I just had one last comment: https://github.com/hundertzehn/mocoapp-api-docs/pull/59

You can use it already.

**Comment by petersentner** [comment]
So the week starts well, very cool :-)
I'll try. Thank you

**Comment by agileapplications** [comment]
Yes, everything online. I close it, you just open it again if sth is not working as expected 👍

**Comment by AlexandreKilian** [comment]
this endpoint is giving me an "invalid API Key" exception while other endpoint don't? same API key

**Comment by pic** [comment]
Hi Alexandre, could you please provide more details?
I've just tried GET `{{full-url}}/api/v1/projects/{project_id}/payment_schedules` it and it was all fine for me.
