### ISSUE TITLE
cash_discount or discount?

### ISSUE THREAD

**Issue by dimy4** [hundertzehn/mocoapp-api-docs#44]
Hello MocoApp Community!

Today, when we created an invoice via API, we got an error message:
`cash_discount: is not a number`

But in the documentation there is only "discount"

![image](https://user-images.githubusercontent.com/2969266/58416657-9ecf4b80-8082-11e9-94a2-a24f219d2f7c.png)

**Comment by agileapplications** [comment]
Hi @dimy4 

Sorry we have an issue here and will fix it tonight. Then the problem will disappear.
We'll will also add meaningful defaults and a some fields won't be mandatory anymore.

Have a look here: https://github.com/hundertzehn/mocoapp-api-docs/pull/43/files

Sorry for the inconvenience.
Best Tobias

**Comment by dimy4** [comment]
Hi Tobias,

then we wait for update!
thank you!

Kind regards
Dima

**Comment by pic** [comment]
Hi @dimy4 ,
the system is updated so it should work as before, best regards
