### ISSUE TITLE
[FEATURE REQUEST] support for GraphQL

### ISSUE THREAD

**Issue by chpio** [hundertzehn/mocoapp-api-docs#46]
Hi,
could you add support for GraphQL?

**Comment by agileapplications** [comment]
We'll implement graphql for internal usage first @chpio. Maybe you have demand we can fulfil with a custom REST endpoint in the meantime...

**Comment by chpio** [comment]
just the usual things:
* efficiently loading only needed data
* getting the data in one request (- pagination) & faster data delivery due to less rate limiting

One thing im missing tho: there's no way to load activities by their project id / task id, at least not a way im aware of, beside loading all activities and then filtering.

**Comment by agileapplications** [comment]
@chpio Ok I see; sadly nothing we can provide in near terms. Bare with me that I close this PR since it's not actionable right now for us. It's on our long term agenda. Feel free to open it up again in a bit of time.

Best Tobias

**Comment by ehrhart-dayy** [comment]
Hey there,
any updates on the graphQL-topic? Would be amazing, instead of the plain REST.
Many thanks and Cheers, Christian
