### ISSUE TITLE
fetch fails with 401

### ISSUE THREAD

**Issue by wirths** [hundertzehn/mocoapp-api-docs#47]
Hi,

the documentation describes curl commands to retrieve API data and these commands are working properly. What is weird though is that fetch responds with an 401 error with exactly the same data as in curl.

# works
```
curl -X GET \
  'https://OURDOMAIN.mocoapp.com/api/v1/projects.json' \
  -H 'Authorization: Token token=OURNICETOKEN'
```
# fails with 401
```
const res = await fetch('https://OURDOMAIN.mocoapp.com/api/v1/invoices', {
        headers: {
          Authorization: 'Token token=OURNICETOKEN'
        },
        mode: 'no-cors'
      })
```

Any idea where I am heading in the wrong direction?

Thanks,
Harald

**Comment by nethad** [comment]
Hi Harald

The first example fetches `projects` and the second fetches `invoices`. I assume the user that belongs to this token has access to projects but not invoices. Could you check that?

**Comment by wirths** [comment]
Hi @nethad,
Thanks for the quick reply. Account has full access and it does not change if calling /projects instead of /invoices - same results.

**Comment by nethad** [comment]
I tried it here @wirths and it's working if you leave out the `mode: 'no-cors'`.

**Comment by wirths** [comment]
If leaving `mode: 'co-cors'` out I receive another error message:

`Access to fetch at 'https://MYDOMAIN.mocoapp.com/api/v1/projects' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

I am running my query within NextJS. @nethad What environment are you using?
Thanks

**Comment by wirths** [comment]
SOLVED - It seems that running the fetch command in a page works but fails in a component with useEffects and NextJS. @nethad Thanks for your support
