### ISSUE TITLE
Handle CORS requests

### ISSUE THREAD

**Issue by sem4phor** [hundertzehn/mocoapp-api-docs#60]
Hello,

I tried to communicate with your REST api from my browser. I set up authorization header, etc. for example getting projects but I get a cors error. seems like you have to enable cors preflight requests on the server...

Request copied as fetch:
```
fetch("https://xxx.mocoapp.com/api/v1/projects", {"credentials":"omit","headers":{"sec-fetch-mode":"no-cors"},"referrer":"http://localhost:8080/","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"OPTIONS","mode":"cors"});
```
JS Console Error:
```
Access to XMLHttpRequest at 'https://zweischneider.mocoapp.com/api/v1/projects' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

If you need more details let me know.

Kindly regards

**Comment by agileapplications** [comment]
Hi @sem4phor – we'll look into this and we'll probably allow it since we have different authorization methods compared to the web frontend. Give us some day to think it through 👍

**Comment by sem4phor** [comment]
@agileapplications I am sorry to bother you but can you estimate a time when this will be implemented? More like one week or one month :D

**Comment by pic** [comment]
Hi @sem4phor , we have prioritized this and we'll try to implement it this week

**Comment by pic** [comment]
Hi @sem4phor , CORS should be allowed for resource under /api/v1/* path now. Best
