### ISSUE TITLE
Invoice Payments filter by date?

### ISSUE THREAD

**Issue by dimy4** [hundertzehn/mocoapp-api-docs#62]
Hi!

Is it possible to filter Invoice Payments by date?

Best regards
Dima

**Comment by agileapplications** [comment]
Hi @dimy4 

Yes it is possible, if you look here in the docs: https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/invoices.md#get-invoices

You can provide `date_from` and `date_to` params to narrow down the date range.

Best Tobias

**Comment by dimy4** [comment]
Hi @agileapplications 

thanks. This works fine with Get Invoice. But i need the **Invoice Payments**, and this filter does not work for me.. :(

![image](https://user-images.githubusercontent.com/2969266/67638533-a58a1500-f8e5-11e9-9e40-f876e9e60503.png)

**Comment by agileapplications** [comment]
Hi @dimy4 completely didn't read this. Sorry – we'll look into this 👍 Getting back to you.

**Comment by agileapplications** [comment]
Hi @dimy4 - now you have it. See the new docs 👍
