### ISSUE TITLE
[FEATURE REQUEST] - endpoint for listing available deal_categories

### ISSUE THREAD

**Issue by sommalia** [hundertzehn/mocoapp-api-docs#68]
Hello.

At the moment when we want to create a deal via api request we must supply deal_category_id but regrettably there is no option available to retrieve the availabe deal_category_id's via api. 

We have to go to the admin dashboard and copy the deal_category_id we want to use manually. 

Maybe an endpoint can be created to list all available categories (something like /deals/categories or /deals/deal_categories would be great).

**Comment by pic** [comment]
hi @sommalia , we'll provide that. Best regards

**Comment by sommalia** [comment]
Thank you 👍

**Comment by pic** [comment]
hi @sommalia , it should work now: https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/deal_categories.md

Let us know if there are any problems, best

**Comment by sommalia** [comment]
Again, thank you. Works very well 😃.
