### ISSUE TITLE
 [FEATURE REQUEST] - Endpoint to get user_id

### ISSUE THREAD

**Issue by jankohlbach** [hundertzehn/mocoapp-api-docs#72]

**Comment by agileapplications** [comment]
@jankohlbach What do you need to do? Can you share some use case details?

**Comment by jankohlbach** [comment]
I already solved it, but I think it would have been nice to have the user_id to get all the entries from just one user, now I got just all entries from all users and filtered them based on their names or mail addresses I think

**Comment by agileapplications** [comment]
Not sure I understood what you mean by "entries" but if you mean activities then you can filter them by user_id: https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/activities.md#get-activities

I close this for now.

**Comment by globin** [comment]
I think the question is that there is no obvious way to retrieve the user_id of the API key, therefore not being able to get the activities of oneself without extra information.
