### ISSUE TITLE
[Feature Request] Add task_id as optional parameter in get-actvities

### ISSUE THREAD

**Issue by sommalia** [hundertzehn/mocoapp-api-docs#77]
Hello,

currently activities have to created with a  _task_id_ in mind
(see https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/activities.md#post-activities).

On the other hand if you retrieve activities from the api  you cannot filter by _task_id_, you have to do it manually.

It would be very nice if _task_id_ could be added as an optional parameter of get-activies.

**Comment by agileapplications** [comment]
Here you go @sommalia https://github.com/hundertzehn/mocoapp-api-docs/commit/bd3b2564d37fddb93bf349155a3931f3459f9e6d

**Comment by sommalia** [comment]
Thank you.
