### ISSUE TITLE
Is it already possible to create new incoming invoices via API?

### ISSUE THREAD

**Issue by coeing** [hundertzehn/mocoapp-api-docs#78]
Hi there,

We plan to connect Moco to a bookkeeping software we are using. Therefore we like to create incoming invoices as "Ausgaben" in Moco via the API. It looks like the API has no endpoints for that yet or am I missing something?

Cheers
Christian

**Comment by coeing** [comment]
Just stumbled upon the open pull request: https://github.com/hundertzehn/mocoapp-api-docs/pull/76 It looks like that's the documentation for it, so can I assume the functionality is already there?

**Comment by agileapplications** [comment]
We are going to release it soon @coeing -> if you use it already it might change slightly. We'll inform people soon. What are you doing exactly? Possible to share your use case?

**Comment by coeing** [comment]
@agileapplications We are thinking about a regular sync of invoice/purchase data from Candis to Moco. Just planning right now, the implementation might not start too soon.

**Comment by agileapplications** [comment]
@coeing Sounds interesting. So go ahead. We merged the docs :clap:
