### ISSUE TITLE
New SchedulesEntities via API

### ISSUE THREAD

**Issue by ibtggmbh-ball** [hundertzehn/mocoapp-api-docs#80]
Hello,

is it possible to read the new schedules-beta items from the Api?
I can't find an schedule Item with hours. Only the with the am und pm flag.
I tried https://xxx.mocoapp.com/api/v1/schedules-beta and similiar but there is no endpoint.

Thanks in advance.

**Comment by pic** [comment]
Hi, unfortunately it's not possible yet but we will add this for sure.
I guess you'll have it before the end of May.
Best regards.

**Comment by agileapplications** [comment]
@ibtggmbh-ball Here you go: https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/planning_entries.md

Best, Tobias
