### ISSUE TITLE
Find contact by phone number

### ISSUE THREAD

**Issue by denunv** [hundertzehn/mocoapp-api-docs#82]
Right now we are using Zapier to get notified in a Slack channel about our missed SIP calls. 
The contact information is stored in MOCO. 
It would be nice to be able to find a MOCO contact by number so that we could add this information in the Slack message.

Am I missing something or is this not possible right now?

**Comment by agileapplications** [comment]
Hi @denunv it's not yet possible but we have another request to search via name. So I add your request to this one and will give you a ping when it's ready.

**Comment by agileapplications** [comment]
Hi @denunv check this one and open the Issue if it's not what you expected: https://github.com/hundertzehn/mocoapp-api-docs/pull/83

Best Tobias

**Comment by denunv** [comment]
Thank you @agileapplications for the quick response. Is this possible with Zapier right now? 
I cannot find the option in the MOCO App/Event.

I did add MOCO (1.5.2) to My Apps. But only MOCO 1.1.0 is available in the Zap.
These are the only options for searching:
<img width="932" alt="Bildschirmfoto 2020-04-29 um 08 45 50" src="https://user-images.githubusercontent.com/1753606/80567703-052cbe80-89f6-11ea-9138-7493cdc1e540.png">

I hope you can help me.

**Comment by denunv** [comment]
Nevermind. I added the MOCO App without version number to my Zapier and found Find Contact. 

But these are the only options (phone is still missing):
<img width="915" alt="Bildschirmfoto 2020-04-29 um 08 52 36" src="https://user-images.githubusercontent.com/1753606/80568209-e549ca80-89f6-11ea-80a8-8f089f6a0b30.png">

**Comment by agileapplications** [comment]
:facepalm: I misread "Zapier". This is now available for the public REST API. Not Zapier. But I'll make sure we'll add it also there.

**Comment by denunv** [comment]
@agileapplications It is now possible in Zapier. Thanks for the support. 👍🏻

**Comment by agileapplications** [comment]
@denunv Great to hear, yes sometimes it takes a day on Zapier for the new version to appear. Thank you for the confirmation :+1:
