### ISSUE TITLE
[FEATURE REQUEST] - Endpoint for sending invoices via email

### ISSUE THREAD

**Issue by CorvS** [hundertzehn/mocoapp-api-docs#87]
Hey there!

I already had a nice chat with Thomas about this.

We would like to automate our invoicing. For that it would be necessary to send an invoice via API.

For now - as a workaround - we send the emails using an email service and attach the invoices manually using the [/invoices/{id}.pdf](https://github.com/hundertzehn/mocoapp-api-docs/blob/master/sections/invoices.md#get-invoicesidpdf) endpoint.

Greetings to Switzerland,

Corvin

**Comment by agileapplications** [comment]
We'll have a look at this @CorvS. But it might take some time. Pretty busy atm with new features to come :muscle:

**Comment by pic** [comment]
This is now available: https://github.com/hundertzehn/mocoapp-api-docs/pull/98/commits/4c96fceb59bba003488f3fb5903b9eedcae409a8
Let us know if there are any problems, best
