### ISSUE TITLE
Endpoint for purchase creation does not work as described

### ISSUE THREAD

**Issue by sommalia** [hundertzehn/mocoapp-api-docs#88]
Hello,

unfortunately the endpoint for purchase creation does not work as described in the documentation.

Our curl statement with just the required parameters gets a 500 response status code.

```
curl -X POST \
  'https://{domain}.mocoapp.com/api/v1/purchases' \
  -H 'Authorization: Token token=YOUR_API_KEY' \
  -H 'Content-Type: application/json' \
  -d '
    {
      "date": "2020-02-02",
      "currency": "EUR",
      "payment_method": "bank_transfer",
      "items": [
        {
          "title": "Ticket",
          "total": 30,
          "tax": 10,
          "tax_included": true,
        }
      ],
    }'
```

**Comment by agileapplications** [comment]
You are also sending `"custom_properties": { "Various" => "Stuff" },` which is not valid JSON. Can you check this @sommalia ?

**Comment by sommalia** [comment]
Yes, we saw that so we left it out of our request. We are just sending with the required parameters (date, currency, payment_method and one item)

```
curl -X POST \
  'https://{DOMAIN}.mocoapp.com/api/v1/purchases' \
  -H 'Authorization: Token token={APIKEY}' \
  -H 'Content-Type: application/json' \
  -d '
    {
      "date": "2020-02-02",
      "currency": "EUR",
      "payment_method": "bank_transfer",
      "items": [
        {
          "title": "Ticket",
          "total": 30,
          "tax": 10,
          "tax_included": true,
        }
      ],
    }'
```

The Response Status code for this request is 400.

**Comment by nethad** [comment]
@sommalia  I highly suspect an issue here with the JSON. Can you delete the last comma after the array literal?

**Comment by nethad** [comment]
Also, the trailing comma in the items object

**Comment by sommalia** [comment]
@nethad Like this?

```
curl -X POST \
  'https://{DOMAIN}.mocoapp.com/api/v1/purchases' \
  -H 'Authorization: Token token={APIKEY}' \
  -H 'Content-Type: application/json' \
  -d '{
      "date": "2020-02-02",
      "currency": "EUR",
      "payment_method": "bank_transfer",
      "items": [
        {
          "title": "Ticket",
          "total": 30,
          "tax": 10,
          "tax_included": true
        }
      ]
    }'
```

Sadly this still fails (with status code 500). I also tried changing the value from tax_included to `True` (and leaving it out) with no success.

**Comment by pic** [comment]
@sommalia we are checking this and we'll get back to you asap, thanks for reporting.

**Comment by sommalia** [comment]
@pic Thank you :)

**Comment by pic** [comment]
@sommalia it should be fixed now, best
