### ISSUE TITLE
[Bug] Invoice: service period Validation

### ISSUE THREAD

**Issue by dennisoderwald** [hundertzehn/mocoapp-api-docs#89]
The fields 'service_period_from' and 'service_period_to' must always be set together. If only one of the fields is set, an error 500 occurs.

Here a 422 message should be returned.

**Comment by pic** [comment]
This will  be fixed soon, thx

**Comment by pic** [comment]
It should be fixed now

**Comment by sunsations** [comment]
Fixed now
