### ISSUE TITLE
[FEATURE REQUEST] Project Expense Recurring Interval

### ISSUE THREAD

**Issue by dennisoderwald** [hundertzehn/mocoapp-api-docs#91]
Unfortunately, it is not possible to see from a Project Expense from which recurring expense it was created or with which interval what would be very important for the calculation of the service period.

An additional service that is calculated every three months has a different service period than a monthly one.

**Comment by agileapplications** [comment]
Hi @dennisoderwald I am not sure the added a reference would make it better. It would move the logic we should implement to our users. We will implement proper service periods for expenses as well.

**Comment by dennisoderwald** [comment]
@agileapplications You got that right. But it would be a temporary solution that we could work with until you can calculate and display the service period.

**Comment by dennisoderwald** [comment]
Is there an estimate at the time of implementation of one of the two variants?

**Comment by agileapplications** [comment]
Hi @dennisoderwald we cannot add temporary solutions in public API without making everything complicated. I guess we could finish this year on this topic. It's also important to us to provide a proper solution.

**Comment by agileapplications** [comment]
@dennisoderwald Small update: We are currently working on adding a "service period" also to an expense. The recurring expense will set that period when it's recurred. If this is done we add the field also to the API. We also automatically set the correct service period on the invoice then.

**Comment by agileapplications** [comment]
@dennisoderwald This is done now: https://github.com/hundertzehn/mocoapp-api-docs/commit/be43457cfd67ffd54cda9637f42ea371af82230a

**Comment by agileapplications** [comment]
@dennisoderwald We changed the implementation to be more flexible (https://github.com/hundertzehn/mocoapp-api-docs/commit/589507a4de7e0c44f6965d888d7a378df12b342f)

For backward compatability one can for now still send the billing_in_advance parameter, it will be mapped accordingly.
