### ISSUE TITLE
[FEATURE REQUEST] Invoice Reminders

### ISSUE THREAD

**Issue by dennisoderwald** [hundertzehn/mocoapp-api-docs#92]
As part of our automation, it would be helpful if we could create invoice reminders using the API. Because there is no bulk function via the frontend.

**Comment by nethad** [comment]
Hi Dennis

We'll put this on our internal agenda and will get back to you. A few of us are on holidays, so it might take ~2 weeks unfortunately, but we'll get back to you!

**Comment by pic** [comment]
Hi Dennis, we have a beta implementation of this: https://github.com/hundertzehn/mocoapp-api-docs/commit/c846d02af43be0342801945b1cd7521faf40c719

We might change something in coming weeks, but it should be quite stable, best.
