### ISSUE TITLE
[QUESTION] Billing email from project

### ISSUE THREAD

**Issue by dennisoderwald** [hundertzehn/mocoapp-api-docs#97]
If I define a different e-mail address below a project in the billing. Where is this response in the API to take it when sending our own e-mail?

**Comment by pic** [comment]
@dennisoderwald it's not yet there. We will add it next week

**Comment by pic** [comment]
@dennisoderwald we are changing some stuff here and so the update on api/V1 will be delayed, sorry

**Comment by dennisoderwald** [comment]
No problem. Approximately a time estimate of how much delay we are talking about?

**Comment by pic** [comment]
@dennisoderwald around 2 weeks.

"It Was Two Minutes Five Minutes Ago." ( https://getyarn.io/yarn-clip/75e6ef88-e3ce-4952-a595-2925cbaa81a3 )

**Comment by dennisoderwald** [comment]
Ping :)

**Comment by agileapplications** [comment]
@dennisoderwald It's online and can be used: https://github.com/hundertzehn/mocoapp-api-docs/commit/cb2461d744bbce31ff9842a79d687f83be3995e9
